# Generated by Django 3.1.4 on 2020-12-21 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_db',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
