# Generated by Django 3.1.4 on 2020-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20201221_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_db',
            name='accuracy_date',
            field=models.CharField(max_length=45),
        ),
    ]
