# Generated by Django 3.1.4 on 2020-12-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20201221_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_db',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
