# Generated by Django 3.1.2 on 2020-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_card_db_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birthday', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_of_wintering_place', models.CharField(max_length=40)),
                ('wintering_place', models.CharField(max_length=40)),
                ('date_of_arrival', models.CharField(max_length=20)),
                ('flight_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feeding_ration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('characteristic', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reptile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_temperature', models.IntegerField(max_length=45)),
                ('hibernation_period', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.IntegerField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('birthday', models.CharField(max_length=45)),
                ('marital_status', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='Author_db',
        ),
        migrations.DeleteModel(
            name='Card_db',
        ),
        migrations.DeleteModel(
            name='Exhibition_db',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
