# Generated by Django 3.1.2 on 2020-12-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20201227_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitat_area',
            name='number',
        ),
        migrations.AddField(
            model_name='habitat_area',
            name='name',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
