# Generated by Django 3.1.2 on 2020-12-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20201228_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding_ration',
            name='number',
        ),
    ]
