# Generated by Django 3.1.2 on 2020-12-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_remove_feeding_ration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
