# Generated by Django 3.1.2 on 2020-12-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_remove_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='code_of_wintering_place',
        ),
    ]
