# Generated by Django 3.1.2 on 2020-12-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20201228_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='reptile',
            name='hibernation_period',
            field=models.TextField(max_length=45, null=True),
        ),
    ]
