# Generated by Django 3.1.2 on 2020-12-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20201229_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reptile',
            name='normal_temperature',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='animal',
            name='area_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.habitat_area'),
        ),
        migrations.AddField(
            model_name='animal',
            name='ration_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.feeding_ration'),
        ),
    ]
