# Generated by Django 3.1.2 on 2020-12-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_auto_20201229_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstapp.habitat_area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='ration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.feeding_ration'),
            preserve_default=False,
        ),
    ]
