# Generated by Django 3.1.2 on 2020-12-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_auto_20201229_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='area',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.habitat_area'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ration',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.feeding_ration'),
        ),
    ]
