# Generated by Django 3.1.2 on 2020-12-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_auto_20201229_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ration_id',
        ),
    ]
