# Generated by Django 3.1.2 on 2020-12-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_auto_20201229_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='areai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.habitat_area'),
        ),
        migrations.AddField(
            model_name='animal',
            name='rationi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.feeding_ration'),
        ),
    ]
