# Generated by Django 3.1.2 on 2020-12-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_auto_20201229_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='areai',
            new_name='area_id',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='rationi',
            new_name='ration_id',
        ),
    ]
