# Generated by Django 3.1.4 on 2020-12-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_auto_20201229_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='caretaker_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_id', to='firstapp.user'),
        ),
        migrations.AddField(
            model_name='animal',
            name='veterenar_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterenar_id', to='firstapp.user'),
        ),
    ]
