# Generated by Django 3.1.4 on 2020-12-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_auto_20201229_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='area_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.habitat_area'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ration_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.feeding_ration'),
        ),
    ]
