# Generated by Django 3.1.4 on 2020-12-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_auto_20201229_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='caretaker_id',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='veterenar_id',
        ),
        migrations.AddField(
            model_name='bird',
            name='animal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.animal'),
        ),
        migrations.AddField(
            model_name='reptile',
            name='animal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.animal'),
        ),
    ]
