# Generated by Django 3.1.4 on 2020-12-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0031_auto_20201229_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reptile',
            name='normal_temperature',
        ),
        migrations.AddField(
            model_name='animal',
            name='caretaker_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_id', to='firstapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='veterenarian_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='veterenarian_id', to='firstapp.user'),
            preserve_default=False,
        ),
    ]
