# Generated by Django 3.1.4 on 2020-12-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_auto_20201229_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='reptile',
            name='normal_temperature',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
